"""empty message

Revision ID: 335cc53c3ac0
Revises: 29304e5cd643
Create Date: 2020-05-02 21:22:30.626481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335cc53c3ac0'
down_revision = '29304e5cd643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('note', 'tittle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('tittle', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
